apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tjpo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-chzt-tenant/integ-app-oqtt/hacbs-test-project-tjpo@sha256:d9a51216ab08d82ae905a8b4438a089b17e484894b61ee88cdab4da73fdc152b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
